config/routes.rb
Rails.application.routes.draw do
  # Admins
  devise_for :admins, path: 'admin', controllers: {
    sessions: 'admin/sessions'
  }
  namespace :admin do
    get '/', to: redirect('/admin/dashboard')
    get '/calendars/month', to: 'calendars#month'
    get '/calendars/day', to: 'calendars#day'
    get '/dashboard', to: 'dashboard#show'
    resources :users
    resources :admins
    namespace :food do
      resources :menus, except: :destroy
    end
    resources :orders, only: [:index, :show]
  end

  # Users
  devise_for :users, path: '/', controllers: {
    registrations: 'user/registrations',
    sessions: 'user/sessions'
  }
  scope module: :user do
    get '/menus/:id', to: 'food/menus#show', as: :food_menu
    get '/dashboard', to: 'dashboard#show'
    resources :orders, except: [:destroy, :edit, :update]
  end

  # Common
  root 'home#index'

  # API
  namespace :api, defaults: { format: 'json' } do
    namespace :v1 do
      namespace :admin do
        mount_devise_token_auth_for 'Admin', at: 'auth', :skip => ['password']
        resources :orders, only: :index
      end
    end
  end

  # Custom error pages
  get '/404', to: "errors#not_found"
  get '/405', to: "errors#method_not_allowed"
  get '/422', to: "errors#unacceptable"
  get '/500', to: "errors#internal_error"
end

app/controllers/admin/calendars_controller.rb
class Admin::CalendarsController < Admin::BaseController
  include Calendarable
  prepare_time_point actions: [:day, :month], param_name: :start_date, fallback_location: :admin_calendars_month_path
  before_action :set_menus, only: [:day, :month]
  before_action :set_orders, only: [:day, :month]

  # GET /admin/calendars/day
  def day
    @date = params[:start_date]
  end

  # GET /admin/calendars/month
  def month
  end

  private

  def set_menus
    @menus = Food::Menu.created_within(@time_point, params[:action])
  end

  def set_orders
    @orders = Order.created_within(@time_point, params[:action]).includes(:food_items)
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def count_items_per_cell(items, date)
    items.select{ |r| date.all_day.cover? r.created_at}.count
  end
end

app/views/admin/calendars/_cell.html.haml
= link_to admin_calendars_day_path(:start_date => date.to_s), class: 'calendar__cell' do
  .badge.badge-pill.badge-light= date.day

  - if menus_count > 0
    %br
    %b Menus:
    = menus_count

  - if orders_count > 0
    %br
    %b Orders:
    = orders_count

app/views/admin/calendars/day.html.haml
%h1 Daily stats

.calendar-heading
  = link_to 'Previous', admin_calendars_day_path(:start_date => (Time.zone.parse(@date) - 1.day).strftime('%Y-%m-%d'))
  %span.calendar-title= @date
  = link_to 'Next', admin_calendars_day_path(:start_date => (Time.zone.parse(@date) + 1.day).strftime('%Y-%m-%d'))

%h3 Menus

= render 'admin/food/menus/collection', menus: @menus

%h3 Orders

%b Total cost per day:
= @orders.reduce(Money.new(0)) { |sum, order| sum + order.total_cost }

= render 'admin/orders/collection', orders: @orders

app/views/admin/calendars/month.html.haml
%h1 Monthly calendars

.calendars
  = month_calendar do |date|
    = render 'admin/calendars/cell',
      date: date,
      menus_count: count_items_per_cell(@menus, date),
      orders_count: count_items_per_cell(@orders, date)